# These are required for the tests

source 'http://rubygems.org'

gem 'rack', '< 1.4'
gem 'iron_worker'
gem 'test-unit'
gem 'jeweler2'
gem 'zip'
gem 'rest'

gem 'activesupport'
gem 'simple_record'
gem 'dropbox', '1.2.3'
gem 'mongoid_i18n'
gem 'signature'
gem 'pusher'
gem 'carrierwave'
gem 'aws-s3'
gem 'mechanize'
