# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simple_worker}
  s.version = "0.3.20"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Travis Reeder"]
  s.date = %q{2011-01-07}
  s.description = %q{I could tell you, but then I'd have to...}
  s.email = %q{travis@appoxy.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "lib/rails2_init.rb",
    "lib/railtie.rb",
    "lib/simple_worker.rb",
    "lib/simple_worker/base.rb",
    "lib/simple_worker/config.rb",
    "lib/simple_worker/service.rb",
    "lib/simple_worker/used_in_worker.rb",
    "rails/init.rb"
  ]
  s.homepage = %q{http://github.com/appoxy/simple_worker}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Classified}
  s.test_files = [
    "test/models/model_1.rb",
    "test/models/model_2.rb",
    "test/requiring_worker.rb",
    "test/scheduled_worker.rb",
    "test/second_worker.rb",
    "test/test_base.rb",
    "test/test_inheritance.rb",
    "test/test_simple_worker.rb",
    "test/test_worker.rb",
    "test/test_worker_2.rb",
    "test/test_worker_3.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<appoxy_api>, [">= 0"])
    else
      s.add_dependency(%q<appoxy_api>, [">= 0"])
    end
  else
    s.add_dependency(%q<appoxy_api>, [">= 0"])
  end
end

